version: 2.1
orbs:
  node: circleci/node@4.2.0
  aws-cli: circleci/aws-cli@2.0.0
jobs:
  frontend:
    working_directory: ~/app/udagram-frontend
    executor: node/default
    steps:
      - checkout:
          path: ~/app
      - node/install-packages:
          app-dir: ~/app/udagram-frontend
      - run:
          name: Build Frontend
          command: npm run build
      - aws-cli/install
      - run:
          name: Deploy Frontend
          command: aws s3 cp --recursive --acl public-read ./www s3://udagram-api/
  server:
    working_directory: ~/app/udagram-api
    executor: node/default
    steps:
      - checkout:
          path: ~/app
      - node/install-packages:
          app-dir: ~/app/udagram-api
      - run:
          name: Build and Archive Server
          command: |-
            npm run build
            printenv > www/.env
      - aws-cli/install
      - run:
          name: Deploy Server
          command: |-
            aws s3 mv ./www/Archive.zip s3://elasticbeanstalk-udagram-api/app/app-dev-$TIMESTAMP.zip
            aws elasticbeanstalk create-application-version --region us-east-1 \
  --application-name udagram-api --version-label development-$TIMESTAMP \
  --source-bundle S3Bucket=elasticbeanstalk-udagram-api,S3Key=app/app-dev-$TIMESTAMP.zip
            aws elasticbeanstalk update-environment --region us-east-1 --environment-name udagram-api-dev \
  --version-label development-$TIMESTAMP

workflows:
  build_and_deploy:
    jobs:
      - frontend
      - server
